config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  resources :articles do
    resource :article_times, only: [:create, :destroy] do
      collection do
          delete '/' => 'article_times#all_destroy'
          get 'congratulation'
        end
    end
  end
  resources :achievements,only: [:index,:destroy,:create]
  resources :users,only: [:show,:edit]
end

app/models/achievement.rb
class Achievement < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user, optional: true
  has_many :article_times, dependent: :destroy
  has_many :achievements
end

app/models/article_time.rb
class ArticleTime < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles, dependent: :destroy
  has_many :article_times, dependent: :destroy
  has_many :achievements, dependent: :destroy
end

app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController
 def index
  @achievements = current_user.achievements

  if @achievement.nil?
        @nil_result = "nil"
  else
        @nil_result = "nil"
  end

 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about, :public_action]
	before_action :configure_permitted_parameters, if: :devise_controller?
	before_action :myarticle

  def set_user
    @user = User.find(params[:id])
  end

	def myarticle
	  if user_signed_in?
	   @article = current_user.articles.last
	  end
	end

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/article_times_controller.rb
class ArticleTimesController < ApplicationController

  def create
    @article = Article.find(params[:article_id])
    @time = @article.time
    @article_times = current_user.article_times.where(article_id: @article.id)
    @count_articles = @article_times.count

    #達成回数を増やす部分
    article_time = @article.article_times.new(user_id: current_user.id)
    article_time.save

    #+1なのはcreate実行時点では達成日数が反映されていないため
    if @count_articles + 1 == @time
      #100%達成の動き
      #実績テーブルに格納
      Achievement.create(
      user_id: current_user.id,
      article_id: @article.id,
      name: @article.name,
      start_time: @article.created_at,
      time: @time
    )
      #実績に情報を映したのでタスクを削除する
      @article_times.destroy_all
      @article.destroy
      redirect_to congratulation_article_article_times_path
    else
      #未達成ならそのページにとどまる
      redirect_to article_path(@article)
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def show
    @article = Article.find_by(id: params[:id])

    @time = @article.time
	  @count_articles = current_user.article_times.count
	  @article_times = sprintf("%.2f",((@count_articles).to_f / @time) * 100)
	  @article_time_graph = 100 - (@article_times).to_f
  end

  def index
    @article = Article.find_by(id: params[:id])
	  #@article_times = @article.article_times
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    @article.save
    redirect_to article_path(@article)
  end

  def destroy
    @article.destroy
    redirect_to root_path
  end


  def article_params
    params.require(:article).permit(:name,:time)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :authenticate_user!

 def show
  @user = current_user
 end

 def edit
     @user = current_user
 end

	def update
    @user = current_user
    	if @user.update(user_params)
           flash[:success] = "登録情報を変更しました"
           redirect_to users_path
        else
           render :edit and return
        end
	end

private

def customer_params
  	params.require(:user).permit(:email, :name)
end
end

app/helpers/achievements_helper.rb
module AchievementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_times_helper.rb
module ArticleTimesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/achievements/index.html.erb
<div class="container">
<div calss="row">
  <div class="col-xs-12">
    <h2 class="head-line title_h2 text-center">実績一覧</h2>
      <% if @achievement.nil? %>
        <table class="table table-striped">
          <thead>
            <tr class="info">
              <th>タスク名</th>
              <th>開始日</th>
              <th>達成日</th>
              <th>日数</th>
            </tr>
          </thead>
          <tbody>
            <% @achievements.each do |achievement| %>
              <tr>
                <td><%= achievement.name %></td>
    		        <td><%= achievement.start_time.strftime('%Y/%m/%d') %></td>
    		        <td><%= achievement.created_at.strftime('%Y/%m/%d') %></td>
    		        <td><%= achievement.time %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <p>実績がありません。</p>
      <% end %>
    </div>
</div>
</div>

app/views/article_times/_check.html.erb
<ul class="choice-list">
  <li class="checkbox check"></li>
</ul>

app/views/article_times/congratulation.html.erb
<h2>おめでとうございます！</h2>

app/views/article_times/create.js.erb
$('.checkbox').click(function(){
  $(this).toggleClass('is-checked');
});

app/views/articles/index.html.erb
<h2>記録する</h2>
<td><%= @article.name %></td>
<%= button_to "カウントボタン", {controller: "article_times", action: "create"} %>
<%#= button_to "ボタン", {controller: 'article_times', action: 'create'}, {method: :POST, class: "mybutton"} %>
<%#= button_to 'Create', hoges_path(hoge: {user_id: current_user.id, body: 'fuga'}) %>
<td><%= link_to "Destroy", article_path, class:"btn-sm btn-danger", method: :delete,remote: true,data: {confirm: "本当に消しますか？"} %></td>

app/views/articles/new.html.erb
<body>
<%= form_with model:@article,local:true do |f| %>
    <div class="form-group">
      <%= f.label :タスク名 %><br>
      <%= f.text_field :name,class: "name" %>
    </div>
    <div class="form-group">
      <%= f.label :何日続けたい？ %><br>
      <%= f.number_field :time,class: "time", size: 10, min: 1%>
    </div>
    <div class="form-group">
      <%= f.submit class: "btn btn-success" %>
    </div>
  <% end %>
</body>

app/views/articles/show.html.erb
<h2>記録</h2>

<div class="col-xs-3 billing">
    <table class="table table-hover table-condensed table-bordered">
      <tr>
      <th class="info"> タスク名:</th>
      <td><%= @article.name %></td>
      </tr>

      <tr>
      <th class="info">開始日:</th>
      <td><%= @article.created_at.strftime("%Y/%m/%d") %></td>
      </tr>

      <tr>
      <th class="info">目標日数:</th>
      <td><%= @article.time %></td>
      </tr>

      <tr>
      <th class="info">達成日数:</th>
      <td><%= @count_articles %></td>
      </tr>

      <tr>
      <th class="info">達成率:</th>
      <td><%= number_to_percentage(@article_times,precision: 0) %></td>
      </tr>

    </table>
</div>

<p class="text-right">
<%= button_to article_article_times_path(@article.id),class: "btn btn-3d-circle",method: :post do %>
  <span class="btn-3d-circle-content">
    <span class="btn-3d-circle-front"><%= number_to_percentage(@article_times,precision: 0) %>
    </span>
  </span>
  <span class="btn-3d-circle-back"><i class="fas fa-mouse-pointer"></i></span>
<% end %>
</p>


<canvas id="myPieChart"></canvas>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js"></script>

  <script>
  var ctx = document.getElementById("myPieChart");
  var myPieChart = new Chart(ctx, {
    type: 'doughnut',
    data: {
      datasets: [{
          backgroundColor: [
              "#BB5179",
              "#FAFF67",
              "#58A27C",
              "#3C00FF"
          ],
          data: [<%= @article_times %>,<%=@article_time_graph%>]
      }]
    },
    options: {
      title: {
        display: true,
        text: ''
      }
    }
  });
  </script>

app/views/articles/show.js.erb
let button = document.querySelector('.button');
let buttonText = document.querySelector('.tick');

const tickMark = "<svg width=\"58\" height=\"45\" viewBox=\"0 0 58 45\" xmlns=\"http://www.w3.org/2000/svg\"><path fill=\"#fff\" fill-rule=\"nonzero\" d=\"M19.11 44.64L.27 25.81l5.66-5.66 13.18 13.18L52.07.38l5.65 5.65\"/></svg>";

buttonText.innerHTML = "Submit";

button.addEventListener('click', function() {

  if (buttonText.innerHTML !== "Submit") {
    buttonText.innerHTML = "Submit";
  } else if (buttonText.innerHTML === "Submit") {
    buttonText.innerHTML = tickMark;
  }
  this.classList.toggle('button__circle');
});

app/views/homes/about.html.erb
<p>about</p>

app/views/homes/top.html.erb
<h2>継続くん</h2>

app/views/layouts/_header.html.erb
<header>
<div class="container">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">継続くん</a>
 <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item">
        <a class="nav-link" href="#"><%= link_to 'ユーザー', user_path(current_user), class: "fas fa-user text-dark pr-3 d-flex " %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#"><%= link_to 'アバウト', home_about_path, class: "fas fa-store text-dark pr-3 d-flex align-items-center" %></a>
      </li>
      <li class="nav-item">
      <% if Article.exists? %>
        <a class="nav-link disabled" href="#"><%= link_to '記録',article_path(@article),class: "fas fa-running text-dark pr-3 d-flex align-items-center" %></a>
      <% else %>
        <a class="nav-link disabled" href="#"><%= link_to 'タスク',new_article_path,class: "fas fa-running text-dark pr-3 d-flex align-items-center" %></a>
      <% end %>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#"><%= link_to '実績', achievements_path, class: "fas fa-store text-dark pr-3 d-flex align-items-center" %></a>
      </li>
      <% else %>
        <%= link_to 'アバウト', home_about_path, class: "fas fa-store text-dark pr-4 d-flex align-items-center" %>
        <%= link_to '新規登録', new_user_registration_path, class: "fas fa-user-plus text-dark pr-4 d-flex align-items-center" %>
        <%= link_to 'ログイン', new_user_session_path, class: "fas fa-sign-in-alt text-dark pr-4 d-flex align-items-center" %>
       <% end %>
       <li class="nav-item">
        <a class="nav-link disabled" href="#"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt text-dark pr-3 d-flex align-items-center" %></a>
      </li>
    </ul>

    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<body style="background-color:#f5f5dc;">
<html>
  <head>
    <title>継続くん</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/05e4a509a5.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<% provide(:title, "マイページ") %>
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
		<h2 class="head-line text-center title_h2">マイページ</h2>
		<p><strong class="information-link"><i class="far fa-user"></i>登録情報</strong>
			<%= link_to " 編集する", edit_user_path(current_user), class: "glyphicon glyphicon-pencil btn btn-success" %>
		</p>

			<table class="table table-bordered table-condensed" >
				<tbody>
					<tr>
						<td class="info col-xs-2">ユーザー名</td>
						<td class="text-left"><%= @user.name %></td>
					</tr>
					<tr>
						<td class="info">メールアドレス</td>
						<td class="text-left"><%= @user.email %></td>
					</tr>
				</tbody>
			</table>
	</div>
</div>